# before docker-compose up
# env TMPDIR=/private$TMPDIR docker-compose up


# $ aws configure
# AWS Access Key ID [None]: ACCESSKEYAWSUSER
# AWS Secret Access Key [None]: sEcreTKey
# Default region name [None]: us-west-2
# Default output format [None]: json


# $ aws --endpoint-url=http://localhost:4566 s3 ls
# $ aws --endpoint-url=http://localhost:4566 s3 mb s3://mybucketramus
# $ aws s3 cp README.md s3://mybucketramus --endpoint-url=http://localhost:4566
# 
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
    #  - SERVICES=${SERVICES- }
      - SERVICES=s3,ec2,apigateway
    #  - DEBUG=${DEBUG- }
      - DEBUG=1
      - DATA_DIR=${DATA_DIR- }
    #  - PORT_WEB_UI=${PORT_WEB_UI- }
      - PORT_WEB_UI=8081
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"