amazonProperties:
#  endpointUrl: https://s3.us-east-2.amazonaws.com
  # us-east-1
  endpointUrl: http://192.168.15.6:4566
  accessKey: ACCESSKEYAWSUSER
  secretKey: sEcreTKey
  bucketName: mybucketramus